### ISSUE TITLE
Conflict with header format of Seurat FindAllMarkers

### ISSUE THREAD

**Issue by olgabaranov** [bioinfo-ibms-pumc/SCSA#18]
The current version of Seurat (v4) seems to export the table naming the log fold change column 'avg_log2FC' while the script expects 'avg_logFC'. It can be fixed by changing the line 370  of the script to fit the new format

**Comment by bioinfo-ibms-pumc** [comment]
Thanks for the suggestion. You have got the right solution. Because it's hard to adapt to all the headers generated by various software, so you may fixed the problem by changing either the script or the title in the current version. I don't know whether it is worth to develop a converter for the data structure yet. But thanks for reminding.
